### ISSUE TITLE
Package suggestions

### ISSUE THREAD

**Issue by annlia** [cran-task-views/CausalInference#7]
Perhaps you may consider adding the following packages under "Structural equation models, do-calculus causal discovery"

BiDAG : implementing sampling methods for DAGs (so for causal discovery) - and enabling Bayesian inference on causal structures https://cran.r-project.org/web/packages/BiDAG/index.html

Bestie: implementing the do-calculus for estimating intervention effects for a given DAG https://cran.r-project.org/web/packages/Bestie/index.html

Thanks

**Comment by iago-pssjd** [comment]
I take advantage of these issu to report also the `bmem` package (https://cran.r-project.org/web/packages/bmem/index.html) as one among the mediation analysis packages

**Comment by zeileis** [comment]
Imke @imkemayer did you or one of your co-maintainers already get round to having a look at this?

**Comment by imkemayer** [comment]
@zeileis thanks for the reminder! I'll work on this issue and the other open issues this week.

**Comment by zeileis** [comment]
Great, thanks, Imke!

**Comment by imkemayer** [comment]
Hi @annlia, thank you for your suggestions and sorry for the huge delay in my response to them.

- the BiDAG package is indeed well developed and documented, but it is not particularly specific to causality related questions and I think a more suitable place for it to be referenced would be the [GraphicalModels](https://cran.r-project.org/web/views/GraphicalModels.html) task view. What do you think?
- as for the Bestie package, we had already considered it at some point but the documentation of this package is very limited, i.e. no vignettes, and in particular in the reference manual the implemented methods are not well described or linked to more detailed scientific reference. We therefore decided not to include this package in the task view. It might make sense to contact the package maintainers to ask them if they would consider improving the documentation of their package. In that case we would of course reconsider its inclusion in the task view.

Thanks again for reaching out to us! These suggestions are very important for us as the field on causal problems and methods is evolving so quickly.

**Comment by imkemayer** [comment]
Hi @iago-pssjd, thank you for this suggestion. And sorry to you as well for this long delay of my response. This package fulfilled the inclusion criteria for the task view and it is now included in the corresponding mediation analysis subsection in the task view ([1d10bb8](https://github.com/cran-task-views/CausalInference/commit/1d10bb857a91fb72a84267327bcd458c2440ab5f)).

**Comment by imkemayer** [comment]
Closing this issue as all suggestions have been checked (decisions are also documented in [1d10bb8](https://github.com/cran-task-views/CausalInference/commit/1d10bb857a91fb72a84267327bcd458c2440ab5f).
